name: Daily Cypress Test
on:
  schedule:
    - cron: 00 22 * * * # 17:00 GMT-5 (22:00 UTC)

  workflow_dispatch: null
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22"
      - name: Install dependencies
        run: npm ci
      - name: Run Cypress tests
        run: pnpm cypress run
